In [4]:
# 쥬피터노트북 셀 스타일 조절 
from IPython.core.display import display, HTML
display(HTML("<style>.container { font-weight: bold !important; }</style>"))
display(HTML("<style>.container { width: 100% !important; }</style>"))

import warnings
warnings.filterwarnings(action='ignore')

In [5]:
import numpy as np

### 넘파이와 리스트와의 차이점 

##### 리스트 
- 데이타형의 혼합 가능 
- 차원 혼합 가능 
- 리스트 연산 : + (연결), * n (반복)

##### 넘파이 배열 = 행열 = 매트릭스  
- 데이타형의 혼합 x, 한가지 데이타형만 가능  
- n 차원인 경우 각 행의 원소수가 같아야한다. 
- 행열 연산 O

In [6]:
# 데이타형의 혼합 가능 
myList = [ 1, True, '홍길동', 4.56]
myList

[1, True, '홍길동', 4.56]

In [7]:
# 차원 혼합 가능 
myList = [ [1, 2, 3,], [True, False], '홍길동', 4.56]
myList

[[1, 2, 3], [True, False], '홍길동', 4.56]

In [8]:
# 리스트간의 연산 : +
list1 = [ 1, 2, 3, 4, 5]
list2 = [ 4, 5, 10, 20]
list1 + list2

[1, 2, 3, 4, 5, 4, 5, 10, 20]

In [9]:
# 리스트간의 연산 : * n
list1*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

# 넘파이 배열 생성 
np.array(리스트)

# 속성 
- shape : 구조 
- size : 길이
- dtype : 데이타형
- ndim : 차원 

In [15]:
# 1차원 
arr1 = np.array([1, 2, 10, 5, 9.5])
# 2차원 = 3*3 
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
print(arr1)
arr1

[ 1.   2.  10.   5.   9.5]


array([ 1. ,  2. , 10. ,  5. ,  9.5])

In [17]:
arr1.ndim, arr1.shape, arr1.size, arr1.dtype

(1, (5,), 5, dtype('float64'))

In [18]:
print(arr2)
arr2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr2.ndim, arr2.shape, arr2.size, arr2.dtype

(2, (3, 3), 9, dtype('int32'))

In [23]:
# len() => 행수
# size => 전체갯수 
len(arr2), arr2.size

(3, 9)

## 초기값이 지정된 넘파이 배열 생성 

- np.zeros(n) : n개로 구성된 넘파이 배열생성. 값은 모두 0 
- np.zeros([n, m])  : n*m 개로 구성된 넘파이 배열생성. 값은 모두 0 
- np.ones(n) : n개로 구성된 넘파이 배열생성. 값은 모두 1
- np.ones([n, m])  : n*m 개로 구성된 넘파이 배열생성. 값은 모두 1
- np.eye(n) : 대각선이 1이고 나머지가 0인 배열 생성 
- np.tri(n) 
- np.arange(start, end, step) : 순차적인 숫자의 조합으로 배열 생성 
- np.random.randint(start, end, n) : 정수 난수로 구성된 배열 생성  

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [26]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [30]:
# np.arange(start, end, step)
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [32]:
# reshape(n, m) : 행열구조 변경 
np.arange(1, 11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [34]:
# 오류 발생 
# np.arange(1, 11).reshape(5,3)

In [52]:
# 난수 배열 
np.random.randint(1, 20, 20)

array([ 5, 19, 11,  1,  7, 10,  5,  8, 17, 13,  1, 10, 16, 13, 16, 13,  6,
        7, 15,  4])

In [54]:
np.random.randint(1, 20, 20).reshape(5,4)

array([[12,  2,  5, 17],
       [15,  4,  5,  5],
       [15, 16,  8, 10],
       [17,  2, 19, 10],
       [14, 13, 14,  2]])

## 넘파이 배열의 연산 

- 같은 자리의 데이타끼리 연산 

In [55]:
arr1 = np.random.randint(1,50, 16).reshape(4,4)
arr2 = np.random.randint(1,50, 16).reshape(4,4)

In [56]:
arr1

array([[11, 49, 30, 23],
       [22,  6, 19, 13],
       [35, 16,  8, 20],
       [34, 29, 23, 21]])

In [57]:
arr2

array([[25,  5, 48, 30],
       [ 7, 25, 47, 48],
       [38, 26, 21, 20],
       [30, 19,  1, 19]])

In [58]:
arr1 + arr2

array([[36, 54, 78, 53],
       [29, 31, 66, 61],
       [73, 42, 29, 40],
       [64, 48, 24, 40]])

In [59]:
arr1 - arr2

array([[-14,  44, -18,  -7],
       [ 15, -19, -28, -35],
       [ -3, -10, -13,   0],
       [  4,  10,  22,   2]])

In [60]:
arr1 % arr2

array([[11,  4, 30, 23],
       [ 1,  6, 19, 13],
       [35, 16,  8,  0],
       [ 4, 10,  0,  2]], dtype=int32)

In [61]:
arr1 / arr2

array([[ 0.44      ,  9.8       ,  0.625     ,  0.76666667],
       [ 3.14285714,  0.24      ,  0.40425532,  0.27083333],
       [ 0.92105263,  0.61538462,  0.38095238,  1.        ],
       [ 1.13333333,  1.52631579, 23.        ,  1.10526316]])

In [63]:
arr1 // arr2

array([[ 0,  9,  0,  0],
       [ 3,  0,  0,  0],
       [ 0,  0,  0,  1],
       [ 1,  1, 23,  1]], dtype=int32)

In [64]:
arr1 * arr2

array([[ 275,  245, 1440,  690],
       [ 154,  150,  893,  624],
       [1330,  416,  168,  400],
       [1020,  551,   23,  399]])

In [66]:
# 전치행열 
arr1.T

array([[11, 22, 35, 34],
       [49,  6, 16, 29],
       [30, 19,  8, 23],
       [23, 13, 20, 21]])

### 행열의 곱 - Dot 연산 
-  np.dot(행열1, 행열2)

In [69]:
# 2행 3열 
arr3 = np.random.randint(1,20, 6).reshape(2,3)

# 3행 2열 
arr4 = np.random.randint(1,20, 6).reshape(3, 2)

In [70]:
arr3

array([[ 4,  3, 19],
       [ 1,  3, 10]])

In [71]:
arr4 

array([[ 2, 12],
       [ 4, 17],
       [12, 12]])

In [73]:
np.dot(arr3,arr4)

array([[248, 327],
       [134, 183]])

In [76]:
# 리스트의 n 곱하기 
[1, 2, 3, 4, 5]*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [77]:
# n을 곱한다. 
arr4 

array([[ 2, 12],
       [ 4, 17],
       [12, 12]])

In [78]:
arr4*5

array([[10, 60],
       [20, 85],
       [60, 60]])

### 넘파이 배열의 인덱싱과 슬라이싱 

- 인덱싱 
```
넘파이배열[row][column]
넘파이배열[row , column]
```

- 슬라이싱 
```
넘파이배열[start:end:step, start:end:step]
```



In [79]:
arr5 = np.random.randint(1,30, 25).reshape(5,5)
arr5

array([[ 2, 19,  3,  9,  2],
       [ 4, 10,  3,  8,  2],
       [11,  2, 27, 24,  4],
       [13,  1,  9, 29, 25],
       [ 2, 22, 19,  1, 24]])

In [81]:
arr5[0, 0], arr5[0][0]

(2, 2)

In [83]:
arr5[-1, -1], arr5[-2, -3]

(24, 9)

In [87]:
# 3행부터 ~ 마지막 행까지 
arr5[2::, ::]

array([[11,  2, 27, 24,  4],
       [13,  1,  9, 29, 25],
       [ 2, 22, 19,  1, 24]])

In [88]:
# 3열부터 ~ 마지막 열까지 
arr5[::, 2::]

array([[ 3,  9,  2],
       [ 3,  8,  2],
       [27, 24,  4],
       [ 9, 29, 25],
       [19,  1, 24]])

In [90]:
# 행과 열을 같이 슬라이싱  
arr5[1:3:, 2::]

array([[ 3,  8,  2],
       [27, 24,  4]])

In [91]:
# 홀수번째 컬럼 출력 
arr5[::, ::2]

array([[ 2,  3,  2],
       [ 4,  3,  2],
       [11, 27,  4],
       [13,  9, 25],
       [ 2, 19, 24]])

In [92]:
# 짝수번째 행 출력 
arr5[::2, ::]

array([[ 2, 19,  3,  9,  2],
       [11,  2, 27, 24,  4],
       [ 2, 22, 19,  1, 24]])

In [84]:
arr5

array([[ 2, 19,  3,  9,  2],
       [ 4, 10,  3,  8,  2],
       [11,  2, 27, 24,  4],
       [13,  1,  9, 29, 25],
       [ 2, 22, 19,  1, 24]])

In [ ]:
# 리스트, 딕셔너리, 튜플, 집합 