In [1]:
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
import numpy as np

### 넘파이와 리스트와의 차이점

##### 리스트
- 데이터형의 혼합 가능
- 차원 혼합 가능
- 리스트 연산 : +(연결), * n(반복)

##### 넘파이 배열 = 행열 = 매트릭스
- 데이터형의 혼합 불가능, 한가지 데이터형만 가능
- n 차원인 경우 각 행의 컬럼(원소)수가 같아야 한다.
- 행렬 연산 O

In [8]:
# 데이터형의 혼합 가능
myList = [1, True, '홍길동', 4.56]
myList

[1, True, '홍길동', 4.56]

In [9]:
# 차원 혼합 가능
myList2 = [[1, 2, 3], [True, False], '홍길동', 4.56]
myList2

[[1, 2, 3], [True, False], '홍길동', 4.56]

In [15]:
# 리스트간의 연산 : +
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 10, 20]
list1 + list2

[1, 2, 3, 4, 5, 4, 5, 10, 20]

In [16]:
# 리스트간의 연산 : * n
list1 * 3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

# 넘파이 배열 생성
np.array(리스트)

# 속성
- shape : 구조
- size : 길이
- dtype : 데이터형
- ndim : 차원

In [27]:
# 1차원
arr1 = np.array([1, 2, 10, 5, 9.5])
# 2차원 = 3*3
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [28]:
print(arr1)
arr1

[ 1.   2.  10.   5.   9.5]


array([ 1. ,  2. , 10. ,  5. ,  9.5])

In [29]:
arr1.ndim, arr1.shape, arr1.size, arr1.dtype

(1, (5,), 5, dtype('float64'))

In [31]:
print(arr2)
arr2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2.ndim, arr2.shape, arr2.size, arr2.dtype

(2, (3, 3), 9, dtype('int32'))

In [33]:
# len() => 행수
# size => 전체 개수
len(arr2), arr2.size

(3, 9)

## 초기값이 지정된 넘파이 배열 생성

- np.zeros(n) : n개로 구성된 넘파이 배열 생성. 값은 모두 0
- np.zeros([n, m]) : n*m 개로 구성된 넘파이 배열생성. 값은 모두 0
- np.ones(n) : n개로 구성된 넘파이 배열 생성. 값은 모두 1
- np.ones([n, m]) : n*m 개로 구성된 넘파이 배열생성. 값은 모두 1
- np.eye(n) : 대각선의 길이와 값이 1이고 나머지가 0인 배열 생성
- np.tri(n) : 좌하단 삼각형으로 1을 채운 배열 생성
- np.arange(start, end, step) : 순차적인 숫자의 조합으로 배열 생성
- np.random.randint(start, end, n) : 정수 형태 n개의 난수로 구성된 배열 생성

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [42]:
# np.arange(start, end, step)
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [48]:
# reshape(n, m) : 행렬 구조 변경
np.arange(1, 11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [50]:
# 행렬 구조가 안맞으면 오류 발생
np.arange(1, 11).reshape(5, 3)

ValueError: cannot reshape array of size 10 into shape (5,3)

In [67]:
# 난수 배열
np.random.randint(1,100,20)

array([73, 15, 61, 69, 38, 78, 21, 56, 34, 70, 68, 89, 96, 43, 57, 10, 14,
       99, 12,  5])

In [68]:
np.random.randint(1,20,20).reshape(5, 4)

array([[19, 11, 11,  4],
       [ 4, 19, 11, 15],
       [17, 16,  3,  4],
       [ 5, 12, 12,  8],
       [16,  2,  1,  4]])

## 넘파이 배열의 연산

- 같은 자리의 데이터끼리 연산

In [70]:
arr1 = np.random.randint(1, 50, 16).reshape(4, 4)
arr2 = np.random.randint(1, 50, 16).reshape(4, 4)

In [72]:
arr1

array([[11,  8, 44, 27],
       [29, 19,  2, 44],
       [20, 33, 12,  8],
       [39, 27, 25,  6]])

In [73]:
arr2

array([[35, 49, 38, 34],
       [ 5, 26, 34, 23],
       [10, 27, 46, 48],
       [ 3, 28, 20, 11]])

In [74]:
arr1 + arr2

array([[46, 57, 82, 61],
       [34, 45, 36, 67],
       [30, 60, 58, 56],
       [42, 55, 45, 17]])

In [75]:
arr1 - arr2

array([[-24, -41,   6,  -7],
       [ 24,  -7, -32,  21],
       [ 10,   6, -34, -40],
       [ 36,  -1,   5,  -5]])

In [76]:
arr1 % arr2

array([[11,  8,  6, 27],
       [ 4, 19,  2, 21],
       [ 0,  6, 12,  8],
       [ 0, 27,  5,  6]], dtype=int32)

In [77]:
arr1 / arr2

array([[ 0.31428571,  0.16326531,  1.15789474,  0.79411765],
       [ 5.8       ,  0.73076923,  0.05882353,  1.91304348],
       [ 2.        ,  1.22222222,  0.26086957,  0.16666667],
       [13.        ,  0.96428571,  1.25      ,  0.54545455]])

In [78]:
arr1 // arr2

array([[ 0,  0,  1,  0],
       [ 5,  0,  0,  1],
       [ 2,  1,  0,  0],
       [13,  0,  1,  0]], dtype=int32)

In [79]:
arr1 * arr2

array([[ 385,  392, 1672,  918],
       [ 145,  494,   68, 1012],
       [ 200,  891,  552,  384],
       [ 117,  756,  500,   66]])

In [81]:
# 전치행렬
arr1.T

array([[11, 29, 20, 39],
       [ 8, 19, 33, 27],
       [44,  2, 12, 25],
       [27, 44,  8,  6]])

In [82]:
# 행렬의 곱 - Dot 연산
# np.dot(행렬1, 행렬2)

In [92]:
# 2행 3열
arr3 = np.random.randint(1, 20, 6).reshape(2, 3)

# 3행 2열
arr4 = np.random.randint(1, 20, 6).reshape(3, 2)

In [94]:
arr3

array([[ 8, 10,  6],
       [18, 17, 13]])

In [95]:
arr4

array([[ 3, 19],
       [19, 16],
       [ 9,  7]])

In [96]:
arr3 * arr4

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [93]:
np.dot(arr3, arr4)

array([[268, 354],
       [494, 705]])

In [100]:
# 리스트의 n 곱하기
[1, 2, 3, 4, 5] * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [101]:
# n을 곱한다.
arr4

array([[ 3, 19],
       [19, 16],
       [ 9,  7]])

In [102]:
arr4 * 5

array([[15, 95],
       [95, 80],
       [45, 35]])

### 넘파이 배열의 인덱싱과 슬라이싱

- 인덱싱
```
넘파이배열[row][column]
넘파이배열[row, column]
```

- 슬라이싱
```
넘파이배열[start:end:step][start:end:step]
넘파이배열[start:end:step, start:end:step]
```

In [103]:
# 리스트, 딕셔너리, 튜플, 집합

In [104]:
arr5 = np.random.randint(1, 30 ,25).reshape(5, 5)
arr5

array([[11, 13,  8, 11, 19],
       [ 3, 25, 16, 15,  5],
       [23, 29, 10, 22, 12],
       [ 7, 15, 13, 10, 12],
       [ 4, 16, 21, 25,  4]])

In [108]:
arr5[0, 0], arr5[0][0]

(11, 11)

In [110]:
arr5[-1, -1], arr5[-2][-3]

(4, 13)

In [118]:
arr5[0:3][1:3]

array([[ 3, 25, 16, 15,  5],
       [23, 29, 10, 22, 12]])

In [120]:
arr5[0:3:2,1:4:2]

array([[13, 11],
       [29, 22]])

In [124]:
# 3행부터 ~ 마지막 행까지
arr5[2::, ::]

array([[23, 29, 10, 22, 12],
       [ 7, 15, 13, 10, 12],
       [ 4, 16, 21, 25,  4]])

In [123]:
# 3열부터 ~ 마지막 열까지
arr5[::, 2::]

array([[ 8, 11, 19],
       [16, 15,  5],
       [10, 22, 12],
       [13, 10, 12],
       [21, 25,  4]])

In [129]:
# 행과 열을 같이 슬라이싱
arr5[2::, 2::]

array([[10, 22, 12],
       [13, 10, 12],
       [21, 25,  4]])

In [130]:
arr5[1:3, 2:]

array([[16, 15,  5],
       [10, 22, 12]])

In [131]:
# 홀수번째 컬럼 출력 
arr5[::, ::2]

array([[11,  8, 19],
       [ 3, 16,  5],
       [23, 10, 12],
       [ 7, 13, 12],
       [ 4, 21,  4]])

## 추가 퀴즈
1) 1~15 구성된 넘파이 배열을 3행 5열로 구성하고 1,3,5 열만 출력하여라 

2) 1~15 구성된 넘파이 배열을 3행 5열로 구성하고 1행1열, 1행4열, 3행1열, 3행 4열만 출력하여라 

3) 1~15 구성된 넘파이 배열을 3행 5열로 구성하고 홀수번째 행만 출력하여라

### 1)

In [136]:
arr_1 = np.arange(1, 16).reshape(3, 5)

In [137]:
arr_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [138]:
arr_1[::,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

### 2)

In [140]:
arr_1[:3:2,::3]

array([[ 1,  4],
       [11, 14]])

### 3)

In [141]:
arr_1[::2,::]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])