In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(a[11])

11


In [ ]:
print(a[len(a)-1])

11


In [ ]:
print(a[-1])

11


In [ ]:
print(a[-2])

10


In [ ]:
print(a[10:])

print(a[-2:])

[10 11]
[10 11]


In [ ]:
# 뒤에서 4개 숫자 합
print(a)
print(a[-4:])
print(np.sum(a[-4:]))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 8  9 10 11]
38


In [ ]:
# Boolean 타입과의 연산 True = 1 / False = 0
print(5*1)
print(5*True)
print(5*False)

5
5
0


In [ ]:
a = np.array([0, 1, 2, 3, 4, 5])
# b = np.array([0, 0, 0, 1, 1, 1])
b = np.array([False, False, False, True, True, True])
print(a*b)

[0 0 0 3 4 5]


In [ ]:
a = np.arange(12)

mask = a%2 == 0
print(a)
print(mask)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ True False  True False  True False  True False  True False  True False]


In [ ]:
a = np.arange(25).reshape((5,5))
mask = np.array([[1,1,1,1,1],
                 [1,0,0,0,1],
                 [1,0,0,0,1],
                 [1,0,0,0,1],
                 [1,1,1,1,1]])
print(a)
print(mask)
print(a*mask)
print(np.sum(a*mask))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[ 0  1  2  3  4]
 [ 5  0  0  0  9]
 [10  0  0  0 14]
 [15  0  0  0 19]
 [20 21 22 23 24]]
192


In [ ]:
a = np.arange(25).reshape((5,5))
# 테두리가 1인 행렬 만들기
mask = np.ones_like(a)
mask[1:-1,1:-1] = 0

print(a)
print(mask)
print(a*mask)
print(np.sum(a*mask))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[ 0  1  2  3  4]
 [ 5  0  0  0  9]
 [10  0  0  0 14]
 [15  0  0  0 19]
 [20 21 22 23 24]]
192


In [ ]:
# a 행렬의 대각선의 평균
a = np.arange(25).reshape((5,5))
mask = np.eye(5)
cnt_mask = np.sum(mask)

#print(a)
#print(mask)
print(a*mask)
print(sum_mask)

print(np.sum(a*mask)/sum_mask)

[[ 0.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.]
 [ 0.  0.  0. 18.  0.]
 [ 0.  0.  0.  0. 24.]]
5.0
12.0


```
Numpy 의 데이터를 추가하거나 삭제하는 것은 추천하지 않음...
굳이 해야한다면 새로 만들어서 쌓는것을 활용
메모리 활용 구조 상...중간에 데이터가 들어가면 연산이 느리다
```

In [ ]:
# 파이썬 리스트에서 삽입
a = [0, 1, 2, 3, 4]
print(a)
a.insert(3, 99)
print(a)

[0, 1, 2, 3, 4]
[0, 1, 2, 99, 3, 4]


### Numpy 차원 확장 - Expand_dim

In [ ]:
a = np.arange(4)
print(a)
print(a.shape)

[0 1 2 3]
(4,)


In [ ]:
a = a.reshape(4,1)
print(a)
print(a.shape)
a = a.reshape(1,4)
print(a)
print(a.shape)
a = a.reshape(2,2)
print(a)
print(a.shape)

[[0]
 [1]
 [2]
 [3]]
(4, 1)
[[0 1 2 3]]
(1, 4)
[[0 1]
 [2 3]]
(2, 2)


In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

a1 = np.expand_dims(a, axis = 1)
print(a1)
print(a1.shape)

a2 = np.expand_dims(a, axis = -1)
print(a2)
print(a2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
(3, 1, 4)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
(3, 4, 1)


In [ ]:
# 차원 확장 연습
a = np.arange(6).reshape(2,3)

a1 = np.expand_dims(a, axis=0)
print(a1)
print(a1.shape)

a2 = np.expand_dims(a, axis=1)
print(a2)
print(a2.shape)

a3 = np.expand_dims(a, axis=2)   # axis = -1
print(a3)
print(a3.shape)

[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)
[[[0 1 2]]

 [[3 4 5]]]
(2, 1, 3)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
(2, 3, 1)


### 차원 축소 - Squeeze

In [ ]:
a = np.arange(12).reshape((1, 3, 4))
print(a)
print(a.shape)

a = np.squeeze(a)
print(a)
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
(1, 3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
# default : 필요없는 1이 있는 차원을 다 없앤다.
a = np.arange(12).reshape((1, 3, 1, 4))
print(a)
print(a.shape)

a = np.squeeze(a)
print(a)
print(a.shape)

[[[[ 0  1  2  3]]

  [[ 4  5  6  7]]

  [[ 8  9 10 11]]]]
(1, 3, 1, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
# 축 지정으로 차원 축소
a = np.arange(12).reshape((1, 3, 1, 4))
a = np.squeeze(a, axis=0)
print(a.shape)

(3, 1, 4)


In [ ]:
a = np.arange(12)

# a = a.reshape((3, 4))
a = a.reshape((3, -1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.arange(12).reshape(3, 4)
print(a)

# 전치 행렬 - Transform
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 축 연산

In [ ]:
# 축 단위로 연산하기
a = np.arange(300).reshape((100, 3))
print(a)
# 합치면 축 하나가 사라진다. axis 에는 없애고자 하는 축 번호를 넣는다고 생각하면 쉽다.
s = np.sum(a, axis=0)
print(s)
print(s.shape)

[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]
 [ 12  13  14]
 [ 15  16  17]
 [ 18  19  20]
 [ 21  22  23]
 [ 24  25  26]
 [ 27  28  29]
 [ 30  31  32]
 [ 33  34  35]
 [ 36  37  38]
 [ 39  40  41]
 [ 42  43  44]
 [ 45  46  47]
 [ 48  49  50]
 [ 51  52  53]
 [ 54  55  56]
 [ 57  58  59]
 [ 60  61  62]
 [ 63  64  65]
 [ 66  67  68]
 [ 69  70  71]
 [ 72  73  74]
 [ 75  76  77]
 [ 78  79  80]
 [ 81  82  83]
 [ 84  85  86]
 [ 87  88  89]
 [ 90  91  92]
 [ 93  94  95]
 [ 96  97  98]
 [ 99 100 101]
 [102 103 104]
 [105 106 107]
 [108 109 110]
 [111 112 113]
 [114 115 116]
 [117 118 119]
 [120 121 122]
 [123 124 125]
 [126 127 128]
 [129 130 131]
 [132 133 134]
 [135 136 137]
 [138 139 140]
 [141 142 143]
 [144 145 146]
 [147 148 149]
 [150 151 152]
 [153 154 155]
 [156 157 158]
 [159 160 161]
 [162 163 164]
 [165 166 167]
 [168 169 170]
 [171 172 173]
 [174 175 176]
 [177 178 179]
 [180 181 182]
 [183 184 185]
 [186 187 188]
 [189 190 191]
 [192 193 194]
 [195 196 197]
 [198 199 

In [ ]:
# 축 단위로 연산하기
a = np.arange(15).reshape((5, 3))
print(a)

# 합치면 축 하나가 사라진다. axis 에는 없애고자 하는 축 번호를 넣는다고 생각하면 쉽다.
s = np.sum(a, axis=0)
print(s)
print(s.shape)


s = np.sum(a, axis=1)
print(s)
print(s.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[30 35 40]
(3,)
[ 3 12 21 30 39]
(5,)


In [ ]:
# 축 단위로 연산하기
a = np.arange(15).reshape((5, 3))
print(a)

# 합치면 축 하나가 사라진다. axis 에는 없애고자 하는 축 번호를 넣는다고 생각하면 쉽다.
s = np.mean(a, axis=0)
print(s)
print(s.shape)


s = np.mean(a, axis=1)
print(s)
print(s.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[6. 7. 8.]
(3,)
[ 1.  4.  7. 10. 13.]
(5,)


In [ ]:
a = np.arange(60).reshape(3,4,5)

# (3, 4)
s = np.sum(a, axis = 2)
print(s.shape)

# (4, 5)
s = np.sum(a, axis = 0)
print(s.shape)

# (3, 5)
s = np.sum(a, axis = 1)
print(s.shape)

(3, 4)
(4, 5)
(3, 5)


In [ ]:
# 데이터 생성
a = np.array([[170, 65],
             [165, 75],
             [171, 70],
             [155, 50],
             [165, 55]])

# 키와 몸무게의 평균
print(np.mean(a, axis = 0))

# 가장 큰 키와, 가장 큰 몸무게 출력
print(np.max(a, axis = 0))

# 가장 큰 키의 idx
print(np.argmax(a, axis = 0))

[165.2  63. ]
[171  75]
[2 1]


In [ ]:
a = np.array([1, 3, 5, 2, 4])
print(np.max(a))
# 최대값을 가진 인덱스 출력
print(np.argmax(a))

5
2


In [ ]:
# axis 여러개 연산
a = np.arange(12).reshape(3, 2, 2)
print(a)
print(np.sum(a, axis = (1, 2)))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
[ 6 22 38]


In [ ]:
# a = np.random.randint(12, size = 12).reshape((3, 4))
# 딥러닝 - 분류에서 출력값 최대인 것 뽑기
a = np.random.rand(12).reshape((4, 3))
print(a)
print(np.argmax(a, axis = 1))

[[0.40018258 0.06936384 0.8007233 ]
 [0.56886213 0.14921921 0.55411777]
 [0.26411814 0.01837613 0.08399395]
 [0.70567038 0.03654132 0.29763488]]
[2 0 0 0]


In [ ]:
a = np.array([3, 7, 5, 1, 8, 6, 4])
print(np.sort(a))
print(np.argsort(a))

[1 3 4 5 6 7 8]
[3 0 6 2 5 1 4]


In [ ]:
a = np.arange(6).reshape(2, 3)
#      arange(start, end, step)
b = np.arange(6, 12).reshape(2, 3)
print(a)
print(b)
print(np.vstack([a, b]))
print(np.hstack([a, b]))
# a라는 array와 b라는 array를 같이 담을 수 있는 c라는 array를 새로 만들어서 채우는 개념
# a, b array는 그대로이므로 행을 추가한 개념은 아니다.
c = np.vstack([a, b])
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
a = np.arange(12).reshape(3, 4)
np.savetxt("my_data.csv", a, delimiter=",")

In [ ]:
b = np.loadtxt('my_data.csv', delimiter=",")
print(b)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [ ]:
# narray 데이터 타입 확인
print(b.dtype)

float64


In [ ]:
# 숫자 타입 변경
print(b.astype(np.int))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.arange(6)
print(a)
print(a.astype(np.float))

[0 1 2 3 4 5]
[0. 1. 2. 3. 4. 5.]


In [124]:
names = np.array(['tom', 'jerry', 'brute', '철수', '영희'])
print(names)
heights = np.array([170, 177, 165, 155, 175])
print(heights)

# quiz. 키를 작은 순에서 높은 순으로 sort
print(np.sort(heights))

# quiz. 정렬된 키의 index 를 출력
print(np.argsort(heights))

# quiz. 키 순서대로 이름 출력 - 인덱스에 넘파이 array를 주면 먹힌다.
height_ordered_index = np.argsort(heights)
print(names[height_ordered_index])

['tom' 'jerry' 'brute' '철수' '영희']
[170 177 165 155 175]
[155 165 170 175 177]
[3 2 0 4 1]
['철수' 'brute' 'tom' '영희' 'jerry']


In [125]:
names = np.array(['tom', 'jerry', 'brute', '철수', '영희'])
heights = np.array([170, 177, 165, 155, 175])

print(names[np.argsort(heights)])

['철수' 'brute' 'tom' '영희' 'jerry']


In [126]:
i = np.array([0, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2])
print(names[i])

['tom' '철수' '영희' 'jerry' 'brute' '철수' '영희' 'jerry' 'brute' '철수' '영희'
 'jerry' 'brute']


In [131]:
category_indexes = np.array([0, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2])
e = np.eye(5)
one_hot_encoded = e[category_indexes]
predicted = np.argmax(one_hot_encoded, axis = 1)
print(predicted)

[0 3 4 1 2 3 4 1 2 3 4 1 2]
